### ISSUE TITLE
New API documentation is missing "/vms" API document

### ISSUE THREAD

**Issue by wahaajsiddiqui** [PaloAltoNetworks/prisma-cloud-docs#164]
## Documentation link

https://cdn.twistlock.com/docs/api/20.12/twistlock_api.html#vms

## Describe the problem

The new API documentation which is (https://prisma.pan.dev/api/cloud/cwpp) is missing documentation on "/vms" API which is in our old documentation. As it is quite important for the workflows for a customer's organization.

Additionally, while using the "/vms" API endpoint, the documentation appears to support pulling back AMI tags. The customer is not finding that to be the case, AMIs that do have tags on them are not returning tags via the /vms API.

## Suggested fix

Please include the "/vms" API documentation in the new documentation version.

**Comment by Pubs-MV** [comment]
Hey @ssugandh , please confirm if this not a supported (versioned) endpoint, and hence is not included in the API reference. 

Inline with our guidance here: 
27 May 2021 - Starting on 14 Jun 2021, we'll publish API documentation for our stable endpoints only.

Stable endpoints have always been fully supported, and we have been committed to minimizing changes to them so that your integrations don't break when upgrading to newer versions of Compute.

Starting with  Iverson (22.01) , we'll further enhance how we support our API with versioned endpoints. All stable endpoints will be versioned. Versioned endpoints will be supported for the current release and the previous two releases (that is, Console will serve all three versions). When you upgrade Compute, integrations can still access the endpoints from previous releases, so you can expect integrations to remain fully functional after upgrades, with full support across three major release cycles.

**Comment by wahaajsiddiqui** [comment]
Hi @ssugandh can you please confirm so that I can provide an update to the customer?

**Comment by ssugandh** [comment]
Hi,

The mentioned endpoints are not versioned or supported for backward
compatibility. These are only "v1" endpoints.

The documentation is only available for the "versioned" or
"supported" endpoints.
