### ISSUE TITLE
GKE documentations

### ISSUE THREAD

**Issue by MorShabiPAN** [PaloAltoNetworks/prisma-cloud-docs#468]
## Documentation link

https://docs.paloaltonetworks.com/prisma/prisma-cloud/22-06/prisma-cloud-compute-edition-admin/install/install-gke
https://docs.paloaltonetworks.com/prisma/prisma-cloud/22-06/prisma-cloud-compute-edition-admin/install/install-gke-autopilot

## Describe the problem

Why are these docs not part of the Enterprise edition docs? 
The docs are also missing the ARM description: https://spring.paloaltonetworks.com/twistlock/twistlock/issues/39581#issuecomment-78710

cc @rcaballeromx @iansk @Pubs-MV

**Comment by rcaballeromx** [comment]
@MorShabiPAN Thank you for filing this issue.
I've looked into it and the problem was that the new pieces of content weren't part of the Enterprise Edition book.
I've addressed the issue in [PR 476](https://github.com/PaloAltoNetworks/prisma-cloud-docs/pull/476)
I also included preparing workloads for multiple architectures as part of the GKE install requirements.
PTAL
